steps:
  # Step 1: Verify the repository is cloned correctly
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Service Account used by Cloud Build:"
        gcloud config get-value account
        echo "Listing contents of /workspace:"
        ls -la /workspace

  # Step 2: Identify changed folders
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace/backend &&
        changed_services=""

        if git diff --name-only HEAD | grep -q 'backend/libs/common/'; then
          changed_services="all"
        else
          for service in api-gateway user-service order-service notification-service billing-service review-service menu-service; do
            if git diff --name-only HEAD | grep -q "backend/apps/${service}"; then
              changed_services="${changed_services} ${service}"
              echo "Service changed: ${service}"
            else
              echo "No changes for service: ${service}"
            fi
          done
        fi
        echo "${changed_services}" > /workspace/backend/changed_services.txt

  # # Step 1: Set up buildx
  # - name: 'gcr.io/cloud-builders/docker'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       docker buildx create --use --name mybuilder
  #       docker buildx inspect --bootstrap

  # Step 3: Build Docker images and push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace/backend &&
        changed_services=$(cat changed_services.txt)

        echo "Previous step changed services: ${changed_services}"

        shared_cache="${_IMAGE_ZONE}.pkg.dev/${_PROJECT_ID}/pito-platform/shared-cache:${_IMAGE_TAG}"
        first_service=true

        services=${changed_services}

        if [ "${changed_services}" = "all" ]; then
          services=("api-gateway" "user-service" "order-service" "notification-service" "billing-service" "review-service" "menu-service")
        else
          IFS=' ' read -r -a services <<< "${changed_services}"
        fi

        echo "Changed services: ${services[@]}"

        for service in "${services[@]}"; do
          image_url="${_IMAGE_ZONE}.pkg.dev/${_PROJECT_ID}/pito-platform/${service}:${_IMAGE_TAG}"

          echo "Build image for service $service -> $image_url"
        done

  # Step 4: Copy changed_services.txt to VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp /workspace/backend/changed_services.txt ${_VM_INSTANCE_NAME}:/data/pito-platform/changed_services.txt --zone ${_ZONE}

  # Step 5: SSH into VM and update relevant containers
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh ${_VM_INSTANCE_NAME} --zone ${_ZONE} --command "
        cd /data/pito-platform &&
        echo \"Listing contents of /data/pito-platform:\" &&
        ls -la /data/pito-platform &&

        changed_services=\$(cat changed_services.txt)
        echo \"changed_services: \${changed_services}\"

        if [ \"\$changed_services\" = \"all\" ]; then
          for service in api-gateway user-service order-service notification-service billing-service review-service menu-service; do
            docker compose pull \$service &&
            docker compose down \$service &&
            docker compose up -d --no-deps \$service
          done
        else
          for service in \$changed_services; do
            docker compose pull \$service &&
            docker compose down \$service &&
            docker compose up -d --no-deps \$service
          done
        fi
        "

  # Step 6: Clean up dangling images to free up space
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh ${_VM_INSTANCE_NAME} --zone ${_ZONE} --command "
        docker image prune -f --filter 'dangling=true'
        "

  # Step 7: Notify Slack about the deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        select_webhook_url=$(gcloud secrets versions access latest --secret="SLACK_WEBHOOK_URL")

        if [ -z "$select_web" ]; then
          echo "Failed to retrieve SLACK_WEBHOOK_URL from Secret Manager."
          exit 1
        fi

        gcloud compute ssh ${_VM_INSTANCE_NAME} --zone ${_ZONE} --command "
        changed_services=\$(cat /data/pito-platform/backend/changed_services.txt)
        services_message=\"No service change.\"

        if [ \"\$changed_services\" = \"all\" ]; then
          services_message=\"All services have changed.\"
        else
          services_message=\"Changed services: \$changed_services\"
        fi

        echo \"\$services_message\"

        curl -X POST -H 'Content-Type: application/json' --data '{
          \"text\": \"[Staging] Deployment of services to ${_VM_INSTANCE_NAME} completed successfully.\"
        }' '$select_webhook_url'
        "

substitutions:
  _BRANCH_NAME: 'staging'
  _VM_INSTANCE_NAME: 'pito-platform-staging'
  _ZONE: 'asia-southeast1-a'
  _PROJECT_ID: 'pito-platform-418503'
  _IMAGE_TAG: 'stg'
  _IMAGE_ZONE: 'asia-southeast1-docker'

options:
  substitution_option: ALLOW_LOOSE

timeout: '1200s'

source:
  repoSource:
    projectId: pito-platform-418503
    repoName: pitovn/pito-platform
    branchName: staging
