syntax = "proto3";

package menu;

import "google/protobuf/timestamp.proto";
import "common.proto";

service MenusService {
  rpc FindStoresByFilter (GetStoreByFilterRequest) returns (GetStoreByFilterResponse);
  rpc FindItemsInStore (GetItemInStoreRequest) returns (GetItemInStoreResponse);
  rpc GetFilterOptions (GetFilterOptionRequest) returns (GetFilterOptionResponse);
  rpc InsertMenuItem (PartnerItemRequest) returns (PartnerItem);
  rpc UpdateMenuItem (UpdateItemRequest) returns (PartnerItem);
  rpc FindStores(FindStoresRequest) returns (FindStoresResponse);
  rpc FindStore(FindStoreRequest) returns (FindStoreResponse);
}

// [START] Find stores by filter
message GetStoreByFilterRequest {
  int32 page = 1;        // Page number for pagination
  int32 page_size = 2;   // Number of items per page
  optional string sort_by = 3;    // Sort by field

  optional StoreFilter filters = 4;
}

message GetStoreByFilterResponse {
  repeated SearchStoreResult stores = 1;
  int32 total = 2;
}

message Store {
  message OpeningHours {
    string open = 1;
    string close = 2;
  }
  string id = 1;
  string partner_id = 2;
  string store_name = 3;
  string introduction = 4;
  string avatar = 5;
  string thumbnail = 6;
  string email = 7;
  string phone = 8;
  bool is_active = 9;
  bool is_vat = 10;
  int32 star_rating = 11;
  float timeliness_rate = 12;
  string cover = 13;
  string menu_status = 14;
  repeated int32 cuisine_types = 15;
  repeated int32 special_dietaries = 16;
  repeated int32 occasion_events = 17;
  repeated int32 service_types = 18;
  int32 min_participants = 19;
  int64 min_preparation_time = 20;
  float min_order_value = 21;
  string store_code = 22;
  string slug = 23;
  string status = 24;
  map<string,OpeningHours> opening_hours = 25;
  google.protobuf.Timestamp updated_at = 26;
}

message SearchStoreResult {
  Store store = 1;
  optional float distance = 2;
  int32 total_completed_orders = 3;
  bool is_open = 4;
}

message StoreFilter {
  message ShippingAddressFilter {
    string address = 1;
    float latitude = 2;
    float longitude = 3;
  }

  message BudgetRangeFilter {
    float min = 1;
    float max = 2;
  }

  optional string keyword = 1;
  optional string shipping_time = 2;
  optional BudgetRangeFilter budget_range = 3;
  optional ShippingAddressFilter shipping_address = 4;
  repeated int32 occasion_events = 5;
  repeated int32 special_dietaries = 6;
  repeated int32 service_types = 7;
  repeated int32 cuisine_types = 8;
  optional int32 rating = 9;
}
// [END] Find stores by filter

// [START] Find products in stores
message GetItemInStoreRequest {
  int32 page = 1;        // Page number for pagination
  int32 page_size = 2;   // Number of items per page
  string sort_by = 3;    // Sort by field

  ItemFilter filters = 4;
}

message GetItemInStoreResponse {
  repeated GetItemInStoreResult items = 1;
  int32 total = 2;
}

message ItemFilter {
  message BudgetRangeFilter {
    float min = 1;
    float max = 2;
  }

  string store_id = 1;
  optional string keyword = 2;
  optional BudgetRangeFilter budget_range = 3;
  repeated int32 occasion_events = 4;
  repeated int32 special_dietaries = 5;
  repeated int32 service_types = 6;
  repeated int32 cuisine_types = 7;
}

message ChoiceOfOption {
  string choice_id = 1;
  string name = 2;
  float base_price = 3;
  bool is_active = 4;
}

message OptionAndChoice {
  string option_id = 1;
  string name = 2;
  bool is_required = 3;
  int32 max_choices = 4;
  bool is_multiple_choice = 5;
  bool is_selection_quantity_allowed = 6;
  repeated ChoiceOfOption choices = 7;
  bool is_active = 8;
  string description = 9;
}

message Item {
  string id = 1;
  string slug = 2;
  string name = 3;
  float base_price = 4;
  string description = 5;
  string extra_description = 6;
  repeated string images = 7;
  string store_id = 8;
  int32 min_quantity = 9;
  int32 max_quantity = 10;
  string unit_type = 11;
  string packaging_type = 12;
  string eating_utensil = 13;
  string special_note = 14;
  int32 unit_quantity = 15;
  int32 preparation_time = 16;
  repeated OptionAndChoice options_and_choices = 17;
  repeated int32 special_dietaries = 18;
  repeated int32 cuisine_types = 19;
  repeated int32 occasion_events = 20;
}

message GetItemInStoreResult {
  Item item = 1;
  repeated FilterOption special_dietaries = 2;
  repeated FilterOption cuisine_types = 3;
  repeated FilterOption occasion_events = 4;
}
// [END] Find products in stores

// [START] Get filter options
message GetFilterOptionRequest {
  string keyword = 1;
}

message GetFilterOptionResponse {
  repeated FilterOption cuisine_types = 1;
  repeated FilterOption occasion_events = 2;
  repeated FilterOption service_types = 3;
  repeated FilterOption special_dietaries = 4;
}

message FilterOption {
  int32 id = 1;
  string name = 2;
}
// [END] Get filter options

message Empty {};

// PARTNER
message Metadata {
  bool has_notes = 1;
  bool has_utensils = 2;
  optional string rejection_reason = 3;
}

message PartnerChoiceOfOption {
  string id = 1;
  string name = 2;
  optional float price = 3;
}

message PartnerOptionsChoices {
  string id = 1;
  bool allow_multiple_selection = 2;
  bool allow_quantity_selection = 3;
  string name = 4;
  optional string description = 5;
  bool is_required = 6;
  int32 max_choices = 7;
  repeated PartnerChoiceOfOption choices = 8;
}

message PartnerItemRequest {
  string name = 1;
  optional float base_price = 2;
  optional string description = 3;
  repeated int32 special_dietaries = 4;
  repeated int32 cuisine_types = 5;
  repeated int32 occasion_events = 6;
  string menu_category = 7;
  repeated string images = 8;
  int32 min_quantity = 9;
  string packaging_type = 10;
  string packaging_unit = 11;
  int32 participant = 12;
  int32 preparation_time = 13;
  string store_id = 14;
  repeated PartnerOptionsChoices options_choices = 15;
  Metadata metadata = 16;
  optional string menuId = 17;
  optional string status = 18;
}

message PartnerItem {
  string id = 1;
  string name = 2;
  float base_price = 3;
  string description = 4;
  repeated FilterOption special_dietaries = 5;
  repeated FilterOption cuisine_types = 6;
  repeated FilterOption occasion_events = 7;
  string menu_category = 8;
  repeated string images = 9;
  int32 min_quantity = 10;
  string packaging_type = 11;
  string packaging_unit = 12;
  int32 participant = 13;
  int32 preparation_time = 14;
  string store_id = 15;
  repeated PartnerOptionsChoices options_choices = 16;
  Metadata metadata = 17;
  string slug = 18;
  string status = 19;
}

message FindStoresRequest {
  common.PaginationRequest pagination = 1;
  repeated common.SortRule sorts = 2;
  repeated common.FilterRule filters = 3;
}

message FindStoresResponse {
  message StoreResponse {
    string id = 1;
    string name = 2;
    string slug = 3;
  }

  repeated StoreResponse stores = 1;
  int32 total_count = 2;
}


message FindStoreRequest {
  optional string id = 1;
  optional string slug = 2;
}

message FindStoreResponse {
  message StoreResponse {

    message Location {
      string ward = 1;
      string region = 2;
      string address = 3;
      string district = 4;
      double latitude = 5;
      double longitude = 6;
    }
  
    message ContactInfo {
      string email = 1;
      string phone = 2;
      string full_name = 3;
    }

    string id = 1;
    string name = 2;
    string slug = 3;
    string description = 4;
    string store_code = 5;

    Location location = 6;
    repeated ContactInfo contacts = 7;
  }

  StoreResponse store = 1;
}

message UpdateItemDetailsRequest {
  optional string name = 1;
  optional float base_price = 2;
  optional string description = 3;
  repeated int32 special_dietaries = 4;
  repeated int32 cuisine_types = 5;
  repeated int32 occasion_events = 6;
  optional string menu_category = 7;
  repeated string images = 8;
  optional int32 min_quantity = 9;
  optional string packaging_type = 10;
  optional string packaging_unit = 11;
  optional int32 participant = 12;
  optional int32 preparation_time = 13;
  optional string store_id = 14;
  repeated PartnerOptionsChoices options_choices = 15;
  optional Metadata metadata = 16;
  optional string menuId = 17;
  optional string status = 18;
}

message UpdateItemRequest {
  string id = 1;
  UpdateItemDetailsRequest update_item_request = 2;
}