syntax = "proto3";

package menu;

import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";
import "common.proto";
import "dish/dish.proto";
import "item/occasion-event.proto";

service MenusService {
  rpc FindStores (FindStoresRequest) returns (FindStoresResponse);
  rpc FindStore (FindStoreRequest) returns (FindStoreResponse);
  rpc FindStoresByFilter (GetStoreByFilterRequest) returns (GetStoreByFilterResponse);
  rpc CalculateDistance (CalculateDistanceRequest) returns (CalculateDistanceResponse);

  rpc FindItemsInStore (GetItemInStoreRequest) returns (GetItemInStoreResponse);
  rpc FindItemsWithPagination (FindItemsWithPaginationRequest) returns (FindItemsWithPaginationResponse);
  rpc FindItem (FindItemRequest) returns (PartnerItem);
  rpc FindItems (FindItemsRequest) returns (FindItemsResponse);
  rpc FindAllCateringPackages (Empty) returns (FindAllCateringPackagesResponse);
  rpc FindAllCateringPackageOptions (FindAllCateringPackageOptionsRequest) returns (FindAllCateringPackageOptionsResponse);
  rpc FindCateringPackages(FindCateringPackagesRequest) returns (FindCateringPackagesResponse);
  rpc FindCateringPackagesAndOccasionEvents (Empty) returns (FindCateringPackagesAndOccasionEventsResponse);
  rpc FindItemsByFilters (FindItemsByFiltersRequest) returns (FindItemsByFiltersResponse);
  rpc FilterItemsWithCateringPackage (FilterItemsWithCateringPackageRequest) returns (FilterItemsWithCateringPackageResponse);

  rpc GetFilterOptions (GetFilterOptionRequest) returns (GetFilterOptionResponse);
  rpc GetStoreDetail (GetStoreDetailRequest) returns (GetStoreDetailResponse);
  rpc InsertMenuItem (PartnerItemRequest) returns (PartnerItem);
  rpc UpdateMenuItem (UpdateItemRequest) returns (PartnerItem);
  rpc UpdateStoreStatus (UpdateStoreStatusRequest) returns (UpdateStoreStatusResponse);
  rpc UpdatePartnerStatus (UpdatePartnerStatusRequest) returns (UpdatePartnerStatusResponse);
  rpc UpdateStore (UpdateStoreRequest) returns (UpdateStoreResponse);

  rpc GetListPartners(GetListPartnersRequest) returns (GetListPartnersResponse);
  rpc GetPartnerDetails(GetPartnerDetailsRequest) returns (GetPartnerDetailsResponse);
  rpc UpdatePartner(UpdatePartnerRequest) returns (UpdatePartnerResponse);

  rpc CreateCateringPackage (CreateCateringPackageRequest) returns (CreateCateringPackageResponse) {}
  rpc UpdateCateringPackage (UpdateCateringPackageRequest) returns (UpdateCateringPackageResponse) {}
  rpc DeleteCateringPackage (DeleteCateringPackageRequest) returns (DeleteCateringPackageResponse) {}

  rpc CreateCateringPackageOption (CreateCateringPackageOptionRequest) returns (CreateCateringPackageOptionResponse) {}
  rpc UpdateCateringPackageOption (UpdateCateringPackageOptionRequest) returns (UpdateCateringPackageOptionResponse) {}
  rpc DeleteCateringPackageOption (DeleteCateringPackageOptionRequest) returns (DeleteCateringPackageOptionResponse) {}
  rpc GetCateringPackageOptions (GetCateringPackageOptionsRequest) returns (GetCateringPackageOptionsResponse);
  rpc AssignOptionsToPackage (AssignOptionsToPackageRequest) returns (AssignOptionsToPackageResponse);

  rpc CountCateringPackagesItems(CountCateringPackagesItemsRequest) returns (CountCateringPackagesItemsResponse);

  rpc CreateDish(dish.CreateDishRequest) returns (dish.CreateDishResponse);
  rpc GetDish(dish.GetDishRequest) returns (dish.GetDishResponse);
  rpc ListDishes(dish.ListDishesRequest) returns (dish.ListDishesResponse);
  rpc UpdateDish(dish.UpdateDishRequest) returns (dish.UpdateDishResponse);
  rpc DeleteDish(dish.DeleteDishRequest) returns (dish.DeleteDishResponse);

  rpc CreateOccasionEvent(occasion.event.CreateOccasionEventRequest) returns (occasion.event.CreateOccasionEventResponse);
  rpc GetOccasionEvent(occasion.event.GetOccasionEventRequest) returns (occasion.event.GetOccasionEventResponse);
  rpc UpdateOccasionEvent(occasion.event.UpdateOccasionEventRequest) returns (occasion.event.UpdateOccasionEventResponse);
  rpc DeleteOccasionEvent(occasion.event.DeleteOccasionEventRequest) returns (occasion.event.DeleteOccasionEventResponse);

  rpc FindOccasionEvents(Empty) returns (FindOccasionEventsResponse);
  rpc FindCuisineTypes(Empty) returns (FindCuisineTypesResponse);
  rpc FindSpecialDietaries(Empty) returns (FindSpecialDietariesResponse);

  rpc FindOnboardingsWithPagination (FindOnboardingsRequest) returns (FindOnboardingsResponse);
}

message FindOnboardingsRequest {
  common.PaginationRequest pagination = 1;
  repeated common.SortRule sorts = 2;     
  repeated common.FilterRule filters = 3;
}

message FindOnboardingsResponse {
  message Onboarding {
    string id = 1;
    google.protobuf.Timestamp created_at = 2;
    google.protobuf.Timestamp updated_at = 3;
    google.protobuf.Struct raw_owner_metadata = 4;
    google.protobuf.Struct raw_business_metadata = 5;
    google.protobuf.Struct raw_bank_account_metadata = 6;
    string status = 7;
    string email_confirmation = 8;
    string partner_type = 9;
    google.protobuf.Struct metadata = 10;
  }

  repeated Onboarding onboardings = 1;
  int32 total_count = 2;
}

// [START] Find stores by filter
message GetStoreByFilterRequest {
  int32 page = 1;        // Page number for pagination
  int32 page_size = 2;   // Number of items per page
  optional string sort_by = 3;    // Sort by field

  optional StoreFilter filters = 4;
}

message GetStoreByFilterResponse {
  repeated SearchStoreResult stores = 1;
  int32 total = 2;
}

message Store {
  message OpeningHours {
    string open = 1;
    string close = 2;
  }
  string id = 1;
  string partner_id = 2;
  string store_name = 3;
  string introduction = 4;
  string avatar = 5;
  string thumbnail = 6;
  string email = 7;
  string phone = 8;
  bool is_active = 9;
  bool is_vat = 10;
  int32 star_rating = 11;
  float timeliness_rate = 12;
  string cover = 13;
  string menu_status = 14;
  repeated int32 cuisine_types = 15;
  repeated int32 special_dietaries = 16;
  repeated int32 occasion_events = 17;
  repeated int32 service_types = 18;
  int32 min_participants = 19;
  int64 min_preparation_time = 20;
  float min_order_value = 21;
  string store_code = 22;
  string slug = 23;
  string status = 24;
  map<string,OpeningHours> opening_hours = 25;
  google.protobuf.Timestamp updated_at = 26;
}

message SearchStoreResult {
  Store store = 1;
  optional float distance = 2;
  int32 total_completed_orders = 3;
  bool is_open = 4;
}

message StoreFilter {
  message ShippingAddressFilter {
    string address = 1;
    float latitude = 2;
    float longitude = 3;
  }

  message BudgetRangeFilter {
    float min = 1;
    float max = 2;
  }

  optional string keyword = 1;
  optional string shipping_time = 2;
  optional BudgetRangeFilter budget_range = 3;
  optional ShippingAddressFilter shipping_address = 4;
  repeated int32 occasion_events = 5;
  repeated int32 special_dietaries = 6;
  repeated int32 service_types = 7;
  repeated int32 cuisine_types = 8;
  optional int32 rating = 9;
}
// [END] Find stores by filter

// [START] Find products in stores
message GetItemInStoreRequest {
  int32 page = 1;        // Page number for pagination
  int32 page_size = 2;   // Number of items per page
  string sort_by = 3;    // Sort by field

  ItemFilter filters = 4;
}

message GetItemInStoreResponse {
  repeated GetItemInStoreResult items = 1;
  int32 total = 2;
}

message ItemFilter {
  message BudgetRangeFilter {
    float min = 1;
    float max = 2;
  }

  string store_id = 1;
  optional string keyword = 2;
  optional BudgetRangeFilter budget_range = 3;
  repeated int32 occasion_events = 4;
  repeated int32 special_dietaries = 5;
  repeated int32 service_types = 6;
  repeated int32 cuisine_types = 7;
}

message ChoiceOfOption {
  string choice_id = 1;
  string name = 2;
  float base_price = 3;
  bool is_active = 4;
}

message OptionAndChoice {
  string option_id = 1;
  string name = 2;
  bool is_required = 3;
  int32 max_choices = 4;
  bool is_multiple_choice = 5;
  bool is_selection_quantity_allowed = 6;
  repeated ChoiceOfOption choices = 7;
  bool is_active = 8;
  string description = 9;
}

message Item {
  string id = 1;
  string slug = 2;
  string name = 3;
  float base_price = 4;
  string description = 5;
  string extra_description = 6;
  repeated string images = 7;
  string store_id = 8;
  int32 min_quantity = 9;
  int32 max_quantity = 10;
  string unit_type = 11;
  string packaging_type = 12;
  string eating_utensil = 13;
  string special_note = 14;
  int32 unit_quantity = 15;
  int32 preparation_time = 16;
  repeated OptionAndChoice options_and_choices = 17;
  repeated int32 special_dietaries = 18;
  repeated int32 cuisine_types = 19;
  repeated int32 occasion_events = 20;
}

message GetItemInStoreResult {
  Item item = 1;
  repeated FilterOption special_dietaries = 2;
  repeated FilterOption cuisine_types = 3;
  repeated FilterOption occasion_events = 4;
}
// [END] Find products in stores

// [START] Get filter options
message GetFilterOptionRequest {
  string keyword = 1;
}

message GetFilterOptionResponse {
  repeated FilterOption cuisine_types = 1;
  repeated FilterOption occasion_events = 2;
  repeated FilterOption service_types = 3;
  repeated FilterOption special_dietaries = 4;
}

message FilterOption {
  int32 id = 1;
  string name = 2;
}
// [END] Get filter options

message Empty {};

// PARTNER
message Metadata {
  bool has_notes = 1;
  bool has_utensils = 2;
  optional string rejection_reason = 3;
  repeated string dining_tools = 4;
  optional bool has_feeding_service = 5;
}

message PartnerChoiceOfOption {
  string id = 1;
  string name = 2;
  optional float price = 3;
  optional int32 quantity = 4;
  optional string quantity_unit = 5;
}

message PartnerOptionsChoices {
  string id = 1;
  bool allow_multiple_selection = 2;
  bool allow_quantity_selection = 3;
  string name = 4;
  optional string description = 5;
  bool is_required = 6;
  int32 max_choices = 7;
  repeated PartnerChoiceOfOption choices = 8;
  optional string type = 9;
  optional int32 max_quantity = 10;
}

message ItemServiceSettings {
  int32 setup_time = 1;
  int32 service_time = 2;
  int32 service_person = 3;
}

message PartnerItemRequest {
  string name = 1;
  optional float base_price = 2;
  optional string description = 3;
  repeated int32 special_dietaries = 4;
  repeated int32 cuisine_types = 5;
  repeated int32 occasion_events = 6;
  string menu_category = 7;
  repeated string images = 8;
  int32 min_quantity = 9;
  optional string packaging_type = 10;
  optional string packaging_unit = 11;
  int32 participant = 12;
  int32 preparation_time = 13;
  string store_id = 14;
  repeated PartnerOptionsChoices options_choices = 15;
  Metadata metadata = 16;
  optional string menuId = 17;
  optional string status = 18;
  optional string order_deadline_at = 19;
  int32 service_type = 20;
  ItemServiceSettings service_settings = 21;
}

message PartnerItem {
  string id = 1;
  string name = 2;
  float base_price = 3;
  string description = 4;
  repeated FilterOption special_dietaries = 5;
  repeated FilterOption cuisine_types = 6;
  repeated FilterOption occasion_events = 7;
  string menu_category = 8;
  repeated string images = 9;
  int32 min_quantity = 10;
  string packaging_type = 11;
  string packaging_unit = 12;
  int32 participant = 13;
  int32 preparation_time = 14;
  string store_id = 15;
  repeated PartnerOptionsChoices options_choices = 16;
  Metadata metadata = 17;
  string slug = 18;
  string status = 19;
  optional string order_deadline_at = 20;
  repeated int32 catering_packages = 21;
  string menu_id = 22;
  int32 service_type = 23;
  ItemServiceSettings service_settings = 24;
  optional string store_slug = 25;
  int32 version = 26;
  optional string service_category = 27;
  optional google.protobuf.Timestamp created_at = 28;
  optional google.protobuf.Timestamp updated_at = 29;
}

message FindOccasionEventsResponse {
  repeated FilterOption occasion_events = 1;
}

message FindCuisineTypesResponse {
  repeated FilterOption cuisine_types = 1;
}

message FindSpecialDietariesResponse {
  repeated FilterOption special_dietaries = 1;
}

message FindStoresRequest {
  common.PaginationRequest pagination = 1;
  repeated common.SortRule sorts = 2;
  repeated common.FilterRule filters = 3;
}

message FindStoresResponse {
  message StoreResponse {

    message Location {
      string ward = 1;
      string region = 2;
      string address = 3;
      string district = 4;
      double latitude = 5;
      double longitude = 6;
    }
  
    message ContactInfo {
      string email = 1;
      string phone = 2;
      string full_name = 3;
    }

    string id = 1;
    string name = 2;
    string slug = 3;
    string description = 4;
    string store_code = 5;

    Location location = 6;
    repeated ContactInfo contacts = 7;
    bool is_vat = 8;

    message BankAccount {
      string bank_name = 1;
      string bank_branch = 2;
      string account_holder = 3;
      string account_number = 4;
    }

    BankAccount bank_account = 9;
    google.protobuf.Timestamp created_at = 10;
    google.protobuf.Timestamp updated_at = 11;
    string status = 12;
    common.StorePerformanceLevel performance_level = 13;
    common.StoreEngagementLevel engagement_level = 14;
  }

  repeated StoreResponse stores = 1;
  int32 total_count = 2;
}


message FindStoreRequest {
  optional string id = 1;
  optional string slug = 2;
}

message FindStoreResponse {
  message StoreResponse {

    message Location {
      string ward = 1;
      string region = 2;
      string address = 3;
      string district = 4;
      double latitude = 5;
      double longitude = 6;
    }
  
    message ContactInfo {
      string email = 1;
      string phone = 2;
      string full_name = 3;
    }

    string id = 1;
    string name = 2;
    string slug = 3;
    string description = 4;
    string store_code = 5;

    Location location = 6;
    repeated ContactInfo contacts = 7;
  }

  StoreResponse store = 1;
}

message UpdateItemDetailsRequest {
  optional string name = 1;
  optional float base_price = 2;
  optional string description = 3;
  repeated int32 special_dietaries = 4;
  repeated int32 cuisine_types = 5;
  repeated int32 occasion_events = 6;
  optional string menu_category = 7;
  repeated string images = 8;
  optional int32 min_quantity = 9;
  optional string packaging_type = 10;
  optional string packaging_unit = 11;
  optional int32 participant = 12;
  optional int32 preparation_time = 13;
  optional string store_id = 14;
  repeated PartnerOptionsChoices options_choices = 15;
  optional Metadata metadata = 16;
  optional string menuId = 17;
  optional string status = 18;
  optional string slug = 19;
  optional string order_deadline_at = 20;
  optional int32 service_type = 21;
  optional ItemServiceSettings service_settings = 22;
}

message UpdateItemRequest {
  string id = 1;
  UpdateItemDetailsRequest update_item_request = 2;
}

message FindItemsWithPaginationRequest {
  common.PaginationRequest pagination = 1;
  repeated common.SortRule sorts = 2;     
  repeated common.FilterRule filters = 3;
  optional string menu_type = 4;
}

message FindItemsWithPaginationResponse {
  repeated PartnerItem items = 1;
  int32 total_count = 2;
}

message FindItemsRequest {
  repeated common.FilterRule filters = 1;
}

message FindItemsResponse {
  message PartnerItem {
    string id = 1;
    string name = 2;
    float base_price = 3;
    string description = 4;
    repeated int32 special_dietaries = 5;
    repeated int32 cuisine_types = 6;
    repeated int32 occasion_events = 7;
    string menu_category = 8;
    repeated string images = 9;
    int32 min_quantity = 10;
    string packaging_type = 11;
    string packaging_unit = 12;
    int32 participant = 13;
    int32 preparation_time = 14;
    string store_id = 15;
    repeated google.protobuf.Struct options_choices = 16;
    google.protobuf.Struct metadata = 17;
    string slug = 18;
    string status = 19;
    optional string order_deadline_at = 20;
    optional float distance = 21;
    int32 service_type = 22;
    repeated int32 catering_packages = 23;
  }

  repeated PartnerItem data = 1;
  optional string error = 3;
}

message CalculateDistanceRequest {
  float latitude = 1;
  float longitude = 2;
  string geolocation = 3;
}

message CalculateDistanceResponse {
  float distance = 1;
}

message FindItemRequest {
  oneof filter {
    string id = 1;
    string slug = 2;
    string status = 3;
  }
}

message FindAllCateringPackagesResponse {
  message PackageOption {
    int32 id = 1;
    string name = 2;
  }

  message CateringPackage {
    int32 id = 1;
    string name = 2;
    bool is_active = 3;
    repeated PackageOption options = 4;
  }

  repeated CateringPackage catering_packages = 1;
}

message CateringPackage {
  int32 id = 1;
  string name = 2;
  bool is_active = 3;
}

message FindAllCateringPackageOptionsRequest {
  repeated common.SortRule sorts = 1;
}

message FindAllCateringPackageOptionsResponse {
  message CateringPackageOption {
    int32 id = 1;
    string name = 2;
    string status = 3;
  }

  repeated CateringPackageOption options = 1;
}

message FindCateringPackagesAndOccasionEventsResponse {
  message OccasionEvent {
    int32 id = 1;
    string name = 2;
    bool is_active = 3;
  }

  message PackageOption {
    int32 id = 1;
    string name = 2;
  }

  message CateringPackage {
    int32 id = 1;
    string name = 2;
    bool is_active = 3;
    repeated PackageOption options = 4;
  }

  repeated CateringPackage catering_packages = 1;
  repeated OccasionEvent occasion_events = 2;
}

message FindItemsByFiltersRequest {
  common.PaginationRequest pagination = 1;
  repeated common.SortRule sorts = 2;
  repeated common.FilterRule filters = 3;
  optional float latitude = 4;
  optional float longitude = 5;
  optional string menu_type = 6;
}

message FindItemsByFiltersResponse {
  message ServiceSetting {
    int32 setup_time = 1;
    int32 service_person = 2;
    int32 service_time = 3;
  }

  message Store {
    string status = 1;
    optional string reopenTime = 2;
    google.protobuf.Struct prepTimes = 3;
  }

  message PartnerItem {
    string id = 1;
    string name = 2;
    float base_price = 3;
    string description = 4;
    repeated FilterOption special_dietaries = 5;
    repeated FilterOption cuisine_types = 6;
    repeated FilterOption occasion_events = 7;
    string menu_category = 8;
    repeated string images = 9;
    int32 min_quantity = 10;
    string packaging_type = 11;
    string packaging_unit = 12;
    int32 participant = 13;
    int32 preparation_time = 14;
    string store_id = 15;
    repeated PartnerOptionsChoices options_choices = 16;
    Metadata metadata = 17;
    string slug = 18;
    string status = 19;
    optional string order_deadline_at = 20;
    optional float distance = 21;
    int32 service_type = 22;
    ServiceSetting service_settings = 23;
    Store store = 24;
    string service_category = 25;
    int32 version = 26;
  }
  repeated PartnerItem items = 1;
  int32 total_count = 2;
}

message FilterItemsWithCateringPackageRequest {
  common.PaginationRequest pagination = 1;
  repeated common.SortRule sorts = 2;
  repeated common.FilterRule filters = 3;
}

message FilterItemsWithCateringPackageResponse {
  message PartnerItem {
    string id = 1;
    string name = 2;
    float base_price = 3;
    string description = 4;
    repeated int32 special_dietaries = 5;
    repeated int32 cuisine_types = 6;
    repeated int32 occasion_events = 7;
    string menu_category = 8;
    repeated string images = 9;
    int32 min_quantity = 10;
    string packaging_type = 11;
    string packaging_unit = 12;
    int32 participant = 13;
    int32 preparation_time = 14;
    string store_id = 15;
    repeated google.protobuf.Struct options_choices = 16;
    google.protobuf.Struct metadata = 17;
    string slug = 18;
    string status = 19;
    optional string order_deadline_at = 20;
    optional float distance = 21;
    int32 service_type = 22;
  }

  repeated PartnerItem data = 1;
  int32 total_count = 2;
  optional string error = 3;
}

message GetStoreDetailRequest {
  string identifier = 1;
}

message GetStoreDetailResponse {
  message Location {
    string ward = 1;
    string region = 2;
    string address = 3;
    string district = 4;
    double latitude = 5;
    double longitude = 6;
  }

  message ContactInfo {
    string email = 1;
    string phone = 2;
    string full_name = 3;
  }

  message BankAccount {
    string bank_name = 1;
    string bank_branch = 2;
    string account_holder = 3;
    string account_number = 4;
  }

  message Image {
    string cover = 1;
    string avatar = 2;
    string thumbnail = 3;
  }

  message CuisineType {
    int32 id = 1;
    string name = 2;
  }

  string id = 1;
  string partner_id = 2;
  string name = 3;
  string store_code = 4;
  string status = 5;
  bool is_vat = 6;
  string slug = 7;
  optional string description = 8;

  Location location = 9;
  Image images = 10;
  repeated ContactInfo contacts = 11;
  BankAccount bank_account = 12;

  google.protobuf.Struct prep_times = 13;
  google.protobuf.Struct metadata = 14;

  google.protobuf.Timestamp created_at = 15;
  google.protobuf.Timestamp updated_at = 16;

  // additional
  repeated CuisineType cuisine_types = 17;
  google.protobuf.Timestamp reopen_time = 18;

  float daily_order_limit = 19;
  float daily_revenue_limit = 20;
}

message UpdateStoreStatusRequest {
  repeated string ids = 1;
  string status = 2;
}

message UpdateStoreStatusResponse {
  bool success = 1;
}

message UpdatePartnerStatusRequest {
  repeated string ids = 1;
  string status = 2;
}

message UpdatePartnerStatusResponse {
  bool success = 1;
}

message GetListPartnersRequest {
  common.PaginationRequest pagination = 1;
  repeated common.SortRule sorts = 2;     
  repeated common.FilterRule filters = 3;
}

message GetListPartnersResponse {
  message Partner {
    string id = 1;
    string name = 2;
    string status = 3;
    google.protobuf.Struct representative_contact = 4;
    string business_address = 5;
    common.BusinessType business_type = 6;
    common.Certification certification = 7;
    google.protobuf.Timestamp created_at = 8;
    google.protobuf.Timestamp updated_at = 9;
    bool is_vat = 10;
  }

  repeated Partner data = 1;
  int32 total_count = 2;
  optional string error = 3;
}

message GetPartnerDetailsRequest {
  string id = 1;
}

message GetPartnerDetailsResponse {
  message Partner {
    string id = 1;
    string name = 2;
    string status = 3;
    common.BusinessType business_type = 4;
    common.Certification certification = 5;
    google.protobuf.Timestamp created_at = 6;
    google.protobuf.Timestamp updated_at = 7;

    google.protobuf.Struct business_info = 8;
    google.protobuf.Struct business_owner = 9;
    google.protobuf.Struct bank_account = 10;
    repeated string service_types = 11;
    int32 service_fee_rate = 12;
    bool is_vat = 13;
  }

  optional Partner data = 1;
  optional string error = 2;
}

// Catering Package
message CreateCateringPackageRequest {
  string name = 1;
}

message CreateCateringPackageResponse {
  int32 id = 1;
}

message UpdateCateringPackageRequest {
  int32 id = 1;
  optional string name = 2;
  optional bool is_active = 3;
}

message UpdateCateringPackageResponse {
  int32 affected_rows = 1;
}

message DeleteCateringPackageRequest {
  int32 id = 1;
}

message DeleteCateringPackageResponse {
  bool success = 1;
}

// Catering Package Option
message GetCateringPackageOptionsRequest {
  int32 package_id = 1;
}

message CreateCateringPackageOptionRequest {
  string name = 1;
}

message CreateCateringPackageOptionResponse {
  int32 id = 1;
}

message UpdateCateringPackageOptionRequest {
  int32 id = 1;
  optional string name = 2;
  optional string status = 3;
}

message UpdateCateringPackageOptionResponse {
  int32 affected_rows = 1;
}

message DeleteCateringPackageOptionRequest {
  int32 id = 1;
}

message DeleteCateringPackageOptionResponse {
  bool success = 1;
}

message CateringPackageOption {
  int32 id = 1;
  string name = 2;
  string status = 3;
}

message GetCateringPackageOptionsResponse {
  repeated CateringPackageOption options = 1;
}

message CountCateringPackagesItemsRequest {
  repeated int32 catering_package_ids = 1;
  repeated string item_status = 2;
  string service_category = 3;
}

message CountCateringPackagesItemsResponse {
  map<int32, int32> data = 1;
}

message FindCateringPackagesRequest {
  repeated common.FilterRule filters = 3;
}

message FindCateringPackagesResponse {
  repeated CateringPackage data = 1;
  optional string error = 2;
}

message AssignOptionsToPackageRequest {
  int32 package_id = 1;
  repeated int32 option_ids = 2;
}

message AssignOptionsToPackageResponse {
  bool success = 1;
}

////////////////////////
// [START] UPDATE STORE
////////////////////////

message UpdateStoreRequest {
  message StoreContactInfo {
    string email = 1;
    string phone = 2;
    string full_name = 3;
  }

  message StoreLocation {
    string ward = 1;
    string region = 2;
    string address = 3;
    string district = 4;
    double latitude = 5;
    double longitude = 6;
  }

  message StoreBankAccount {
    string bank_name = 1;
    string bank_branch = 2;
    string account_holder = 3;
    string account_number = 4;
  }

  message StoreImage {
    string cover = 1;
    string avatar = 2;
    string thumbnail = 3;
  }

  message SectionInterval {
    string open = 1;
    string close = 2;
  }

  message PrepTime {
    bool is_active = 1;
    repeated SectionInterval section_intervals = 2;
  }

  message PrepTimes {
    PrepTime monday = 1;
    PrepTime tuesday = 2;
    PrepTime wednesday = 3;
    PrepTime thursday = 4;
    PrepTime friday = 5;
    PrepTime saturday = 6;
    PrepTime sunday = 7;
  }

  message Metadata {
    string store_slug = 1;
    string region_slug = 2;
  }

  string id = 1;
  optional string store_name = 2;
  optional StoreImage images = 3;
  optional bool is_vat = 4;
  optional string description = 5;
  repeated StoreContactInfo contacts = 6;
  optional StoreLocation location = 7;
  optional StoreBankAccount bank_account = 8;
  optional int32 engagement_level = 9;
  optional int32 performance_level = 10;
  Metadata metadata = 11;
}

message UpdateStoreResponse {
  int32 affected_rows = 1;
}

// [END] UPDATE STORE

////////////////////////
// [START] UPDATE PARTNER
////////////////////////

message UpdatePartnerRequest {
  message CitizenImage {
    string path = 1;
    string type = 2;
  }

  message CitizenInfo {
    string citizen_id = 1;
    string issue_date = 2;
    string expiry_date = 3;
    string issue_place = 4;
    repeated CitizenImage citizen_images = 5;
    string resident_address = 6;
  }

  message BusinessOwner {
    string email = 1;
    string phone = 2;
    string full_name = 3;
    CitizenInfo citizen_info = 4;
  }

  message BankFinancialManager {
    string email = 1;
    string phone = 2;
    string full_name = 3;
  }

  message BankAccountInfo {
    string bank_name = 1;
    string bank_branch = 2;
    string account_holder = 3;
    string account_number = 4;
    BankFinancialManager financial_manager = 5;
  }

  message BusinessInfo {
    string tax_code = 1;
    string business_name = 2;
    string business_type = 3;
    string registration_date = 4;
    string registered_address = 5;
    string registration_number = 6;
    repeated string business_licenses = 7;
  }

  string id = 1;
  optional  string name = 2;
  optional  string status = 3;
  optional int32 serviceFeeRate = 4;
  optional common.BusinessType businessType = 5;
  optional common.Certification certification = 6;
  BankAccountInfo bankAccount = 7;
  BusinessInfo businessInfo = 8;
  BusinessOwner businessOwner = 9;
  optional bool isVat = 10;
  repeated string serviceTypes = 11;
}

message UpdatePartnerResponse {
  int32 affected_rows = 1;
}

// [END] UPDATE PARTNER
