syntax = "proto3";

package order;

import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";
import "common.proto";

service OrdersService {
  rpc UpdateOrderStatus (UpdateOrderStatusRequest) returns (UpdateOrderResponse);
  rpc UpdateStoreOrderStatus(UpdateStoreOrderStatusRequest) returns (UpdateStoreOrderResponse);
  rpc FindOrder (FindOrderRequest) returns (FindOrderResponse);
  rpc FindStoreOrder (FindStoreOrderRequest) returns (FindStoreOrderResponse);
  rpc FindOrders (FindOrdersRequest) returns (FindOrdersResponse);
}

// Request message for UpdateOrderStatus
message UpdateOrderStatusRequest {
  string id = 1;
  string status = 2;
  oneof extra_fields {
    string cancel_reason = 3;
    google.protobuf.Timestamp timestamp = 4;
    int32 delivery_eta = 5;
  }
}
message UpdateOrderResponse {
  Order order = 1;
}

// Request message for UpdateStoreOrderStatus
message UpdateStoreOrderStatusRequest {
  string id = 1;
  string status = 2;
}
message UpdateStoreOrderResponse {
  string id = 1;
  string status = 2;
}

// Request message for FindOrder
message FindOrderRequest {
  oneof filter {
    string id = 1;
    string order_code = 2;
    string status = 3; 
  }
}
message FindOrderResponse {
  Order order = 1;
}


// Request message for FindStoreOrder
message FindStoreOrderRequest {
  oneof filter {
    string id = 1;
    string order_code = 2;
    string order_id = 3;
    string status = 4; 
  }
}
message FindStoreOrderResponse {
  StoreOrder store_order = 1;
}

// message OrderFilterDto {
//   string user_id = 1;
//   string keyword = 2;
//   string status = 3;
//   string from_date = 4;
//   string to_date = 5;
//   string delivery_date = 6;
//   string sort_by = 7;
//   string sort_direction = 8;
//   string page_size = 9;
//   string from = 10;
// }

// Message for Order Items
message OrderItem {
  float total_price = 1;
  int32 quantity = 2;
  string notes = 3;
  // repeated string raw_options_choices = 8;

  message Item {
    string id = 1;
    string name = 2;
    string slug = 3;
    repeated string images = 4;
    float base_price = 5;
  }

  Item item = 4;
}

// Message for Order
message Order {
  string id = 1;
  string store_id = 2;
  string user_id = 3;
  common.OrderType order_type = 4;
  string order_code = 5;

  // Price-related fields
  double total_price = 6;
  double sub_total_price = 7;
  double shipping_fee = 8;
  double discount_amount = 9;
  double discount_shipping_fee = 10;

  // Payment method
  common.PaymentMethod payment_method = 11;

  // Status and dates
  common.OrderStatus status = 12;
  google.protobuf.Timestamp delivery_at = 13;
  google.protobuf.Timestamp delivery_failed_at = 14;
  google.protobuf.Timestamp completed_at = 15;
  google.protobuf.Timestamp cancelled_at = 16;
  google.protobuf.Timestamp prepared_at = 17;
  google.protobuf.Timestamp confirmed_at = 18;

  // Delivery-related information
  string receiver_name = 19;
  string receiver_phone = 20;
  string delivery_address = 21;
  int32 delivery_eta = 22;
  optional string tracking_url = 23;
  google.protobuf.Timestamp delivery_date = 24;

  // Cancellation and additional details
  optional string cancel_reason = 25;
  bool delivery_later = 26;
  optional string note = 27;
  repeated OrderItem order_items = 28;
  google.protobuf.Struct vat_info = 29;
  string order_count = 30;
  int32 error_code = 31;
  google.protobuf.Struct metadata = 32;
  string receiver_email = 33;

  // Timestamps
  google.protobuf.Timestamp created_at = 34;
  google.protobuf.Timestamp updated_at = 35;
}

// Message for Store Order
message StoreOrder {
  string id = 1;
  string status = 2;
}

message Orders {
  repeated Order orders = 1;
  int32 total = 2;
}

// GetOrderRequest with pagination
message FindOrdersRequest {
  common.PaginationRequest pagination = 1;
  repeated common.SortRule sorts = 2;     

  // Filtering criteria
  // message OrderFilter {
  //   optional string status = 1;
  //   optional string user_id = 2;
  //   optional string order_code = 3; 
  //   optional string from_date = 4;
  //   optional string to_date = 5;
  //   optional string store_id = 6;
  // }

  repeated common.FilterRule filters = 3;
}

message FindOrdersResponse {
  repeated Order orders = 1;
  int32 total_count = 2;
}
