syntax = "proto3";

package order;

import "google/protobuf/timestamp.proto";

service OrdersService {
  rpc UpdateOrderStatus (OrderUpdateStatusDto) returns (OrderUpdateResponse);
  rpc FindOrders (OrderFilterDto) returns (Orders);
  rpc FindOneOrder (FindOneOrderDto) returns (OrderResponse);
  rpc FindOrdersWithPagination (QueryOrderWithPagination) returns (OrderWithPagination);
}

message OrderResponse {
  optional Order data = 1;
}

message OrderUpdateStatusDto {
  string order_id = 1;
  string status = 2;
  optional string reason = 3;
}

message OrderUpdateResponse {
  string message = 1;
  int32 statusCode = 2;
  bool success = 3;
}

message OrderFilterDto {
  string user_id = 1;
  string keyword = 2;
  string status = 3;
  string from_date = 4;
  string to_date = 5;
  string delivery_date = 6;
  string sort_by = 7;
  string sort_direction = 8;
  string page_size = 9;
  string from = 10;
}

message FindOneOrderDto {
  string id = 1;
}

// Message for Order Items
message OrderItem {
  string item_id = 1;
  string item_name = 2;
  string item_slug = 3;
  float price = 4;
  int32 quantity = 5;
  float total_price = 6;
  string notes = 7;
  repeated string raw_options_choices = 8;

  message Item {
    string id = 1;
    string name = 2;
    string slug = 3;
    int32 index = 4;
    repeated string images = 5;
    string store_id = 6;
    bool is_active = 7;
    string unit_type = 8;
    float base_price = 9;
    string created_at = 10;
    string deleted_at = 11;
    string fts_vector = 12;
    string updated_at = 13;
    string description = 14;
    bool setup_party = 15;
    int32 max_quantity = 16;
    int32 min_quantity = 17;
    string special_note = 18;
    repeated int32 cuisine_types = 19;
    repeated int32 service_types = 20;
    int32 unit_quantity = 21;
    string eating_utensil = 22;
    string packaging_type = 23;
    repeated string occasion_events = 24;
    string menu_category_id = 25;
    int32 preparation_time = 26;
    bool server_available = 27;
    string extra_description = 28;
    repeated int32 special_dietaries = 29;
    string options_and_choices = 30;
  }

  Item item = 9;
}

// Message for Order
message Order {
  string order_id = 1;
  string store_name = 2;
  string introduction = 3;
  string slug = 4;
  string thumbnail = 5;
  string avatar = 6;
  string order_code = 7;
  float total_price = 8;
  string note = 9;
  string receiver_name = 10;
  string status = 11;
  int32 error_code = 12;
  string payment_method = 13;
  google.protobuf.Timestamp created_at = 14;
  google.protobuf.Timestamp delivery_date = 15;

  repeated OrderItem order_items = 16;
}

message Orders {
  repeated Order orders = 1;
  int32 total = 2;
}

// Enum for sorting direction
enum SortDirection {
  ASC = 0;
  DESC = 1;
}

// GetOrderRequest with pagination
message QueryOrderWithPagination {
  int32 page = 1;        // Page number for pagination
  int32 page_size = 2;   // Number of items per page

  // Filtering criteria
  message OrderFilter {
    optional string status = 1;
    optional string keyword = 2;
    optional string from_date = 3;
    optional string to_date = 4;
  }

  // Sorting criteria
  message OrderSort {
    string field = 1;
    SortDirection direction = 2;
  }

  OrderFilter filters = 3; // List of filters for querying orders
  repeated OrderSort sorts = 4;     // List of sorting criteria
}

message OrderWithPagination {
  repeated Order orders = 1;
  int32 total = 2;
}
