syntax = "proto3";

package user;

import "common.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";

service UsersService {
  rpc GetCustomerProfile (GetCustomerProfileRequest) returns (GetCustomerProfileResponse) {}
  rpc GetPartnerProfile (GetUserPartnerProfileRequest) returns (GetUserPartnerProfileResponse) {}
  rpc GetOperatorProfile (GetUserPartnerProfileRequest) returns (GetUserPartnerProfileResponse) {}
  // rpc QueryUsers (stream PaginationDto) returns (stream Users) {}
  rpc GetCustomers (GetCustomersRequest) returns (GetCustomersResponse) {}
  rpc GetCompanies (GetCompaniesRequest) returns (GetCompaniesResponse) {}
  rpc ValidateUserInPartner (ValidateUserInPartnerRequest) returns (BooleanResponse) {}
  rpc ValidateUserInStore (ValidateUserInStoreRequest) returns (BooleanResponse) {}
}

message GetCustomerProfileRequest {
  string user_id = 1;
}

message GetCustomerProfileResponse {
  string id = 1;
  string email = 2;
  optional string phone = 3;
  string first_name = 4;
  string last_name = 5;
  optional string avatar = 6;
  optional string thumbnail = 7;
  optional string contact_address = 8;

  message DeliveryAddress {
    string name = 1;
    string label = 2;
    string type = 3;
    bool default = 4;
  }
  repeated DeliveryAddress delivery_addresses = 9;

  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  int32 status = 12;
  optional string company_id = 13;
}

message GetPartnerProfileRequest {
  string user_id = 1;
}

message GetPartnerProfileResponse {
  string id = 1;
  google.protobuf.Timestamp created_at = 2;
  string partner_name = 3;
  google.protobuf.Timestamp updated_at = 4;
  bool is_active = 5;
  string status = 6;
  BusinessInfo business_info = 7;
  BusinessOwner business_owner = 8;
  BankAccount bank_account = 9;
  string partner_type = 10;
  repeated string service_types = 11;
  optional int32 service_fee_rate = 12; // Use int32 for smallint
  bool is_vat = 13;

  message BankAccount {
    string bank_name = 1;
    string bank_branch = 2;
    string account_holder = 3;
    string account_number = 4;
  }

  message BusinessInfo {
    string tax_code = 1;
    string business_name = 2;
    string business_type = 3;
    string registration_date = 4;
    string registration_address = 5;
    string registration_number = 6;
  }

  message BusinessOwner {
    string email = 1;
    string phone = 2;
    string full_name = 3;
  }
}

message GetOperatorProfileRequest {
  string user_id = 1;
}

message GetOperatorProfileResponse {
  string id = 1;
  google.protobuf.Timestamp created_at = 2;
  google.protobuf.Timestamp updated_at = 3;
  string name = 4;
  string email = 5;
  optional string phone = 6;
  google.protobuf.Struct metadata = 7;
  optional string avatar_url = 8;
  optional string first_name = 9;
  optional string last_name = 10;
}

message GetUserPartnerProfileRequest {
  string user_id = 1;
}

message GetUserPartnerProfileResponse {
  string id = 1;
  optional string full_name = 2;
  string email = 3;
  optional string phone = 4;
  optional string avatar_url = 5; 

  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;

  repeated string roles = 8;
}

message Empty {};

message GetCustomersRequest {
  common.PaginationRequest pagination = 1;
  repeated common.SortRule sorts = 2;     
  repeated common.FilterRule filters = 3;
}

message GetCustomersResponse {
  repeated GetCustomerProfileResponse data = 1;
  int32 total_count = 2;
  optional string error = 3;
}

message GetCompaniesRequest {
  common.PaginationRequest pagination = 1;
  repeated common.SortRule sorts = 2;     
  repeated common.FilterRule filters = 3;
}

message GetCompaniesResponse {
  message Company {
    string id = 1;
    string name = 2;
    string email = 3;
    string phone = 4;
    string address = 5;
    string tax_code = 6;
    google.protobuf.Timestamp created_at = 7;
    google.protobuf.Timestamp updated_at = 8;
  }

  repeated Company data = 1;
  int32 total_count = 2;
  optional string error = 3;
}

message ValidateUserInPartnerRequest {
  string user_id = 1;
  string partner_id = 2;
}

message ValidateUserInStoreRequest {
  string user_id = 1;
  string store_id = 2;
}

message BooleanResponse {
  bool value = 1;
}