const fs = require('fs');
const path = require('path');

const folders = ['./libs/common/src/types/proto', './libs/common/src/types/google/protobuf'];

folders.forEach(folder => {
  fs.readdirSync(folder)
    .filter(file => file.endsWith('.ts'))
    .forEach(file => {
      console.log('file', file);
      const filePath = path.join(folder, file);
      const content = fs.readFileSync(filePath, 'utf-8');

      const updatedContent = content.replace(
        /^\/\/ Code generated by.*\n\/\/ versions:\n\/\/.*protoc-gen-ts_proto.*\n\/\/.*protoc.*\n\/\/ source: .+$/gm,
        '',
      );

      fs.writeFileSync(filePath, updatedContent);
    });
});

console.log('Removed protoc headers from generated files.');
