const fs = require('fs');
const path = require('path');

const folders = [
  './libs/common/src/types/proto',
  './libs/common/src/types/google/protobuf',
  './libs/common/src/types/proto/payment',
];

// Recursive function to get all files in subfolders
const getAllFiles = (dirPath, filesArray = []) => {
  const files = fs.readdirSync(dirPath);

  files.forEach(file => {
    const filePath = path.join(dirPath, file);

    if (fs.statSync(filePath).isDirectory()) {
      // If it's a directory, recurse into it
      getAllFiles(filePath, filesArray);
    } else if (filePath.endsWith('.ts')) {
      // Add .ts files to the list
      filesArray.push(filePath);
    }
  });

  return filesArray;
};

folders.forEach(folder => {
  const allFiles = getAllFiles(folder);

  allFiles.forEach(filePath => {
    console.log('Processing file:', filePath);

    const content = fs.readFileSync(filePath, 'utf-8');

    const updatedContent = content.replace(
      /^\/\/ Code generated by.*\n\/\/ versions:\n\/\/.*protoc-gen-ts_proto.*\n\/\/.*protoc.*\n\/\/ source: .+$/gm,
      '',
    );

    // Write the updated content back to the file
    fs.writeFileSync(filePath, updatedContent);
  });
});

console.log('Removed protoc headers from generated files.');
