export const USER_SERVICE = 'USER_SERVICE';
export const BILLING_SERVICE = 'BILLING_SERVICE';
export const ORDER_SERVICE = 'ORDER_SERVICE';
export const PROMOTION_SERVICE = 'PROMOTION_SERVICE';
export const REVIEW_SERVICE = 'REVIEW_SERVICE';
export const MENU_SERVICE = 'MENU_SERVICE';
