syntax = "proto3";

package payment;

message CreateVnpayUrlPaymentRequest {
  string order_id = 1;
  string order_code = 2;
  int64 amount = 3;
  string bank_code = 4;
  optional string locale = 5;
  string callback_url = 6;
  string ip_addr = 7;
}

message CreateVnpayUrlPaymentResponse {
  string payment_url = 1;
}

message HandleIpnVnpayRequest {
  string vnp_amount = 1;
  string vnp_bank_code = 2;
  string vnp_bank_tran_no = 3;
  string vnp_card_type = 4;
  string vnp_order_info = 5;
  string vnp_pay_date = 6;
  string vnp_response_code = 7;
  string vnp_tmn_code = 8;
  string vnp_transaction_no = 9;
  string vnp_txn_ref = 10;
  string vnp_secure_hash = 11;
  string vnp_transaction_status = 12;
}

message HandleIpnVnpayResponse {
  string RspCode = 1;
  string Message = 2;
}
