syntax = "proto3";

package payment;

message CreateVnpayUrlPaymentRequest {
  string order_id = 1;
  string order_code = 2;
  int64 amount = 3;
  string bank_code = 4;
  string locale = 5;
  string url_callback = 6;
}

message CreateVnpayUrlPaymentResponse {
  string vnpay_url = 1;
}

message HandleIPNRequest {
  string vnp_Amount = 1;
  string vnp_BankCode = 2;
  string vnp_BankTranNo = 3;
  string vnp_CardType = 4;
  string vnp_OrderInfo = 5;
  string vnp_PayDate = 6;
  string vnp_ResponseCode = 7;
  string vnp_TmnCode = 8;
  string vnp_TransactionNo = 9;
  string vnp_TxnRef = 10;
  string vnp_SecureHash = 11;
  string vnp_TransactionStatus = 12;
}
