# version: '3.8'
services:
  # postgres:
  #   image: postgres:17
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #     # - ./init_review.sql:/docker-entrypoint-initdb.d/init_review.sql
  #   networks:
  #     - platform_net
  #   ports:
  #     - "5432:5432"

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - /var/lib/rabbitmq_data:/var/lib/rabbitmq
    networks:
      - platform_net

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    # command: redis-server --appendonly yes
    volumes:
      - /var/lib/redis_data:/data
    networks:
      - platform_net

  typesense:
    image: typesense/typesense:27.1 # fixed version
    restart: on-failure
    ports:
      - '8108:8108'
    env_file:
      - .env
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY}'
    networks:
      - platform_net

volumes:
  rabbitmq_data:
    # driver: local
  redis_data:
    # driver: local

networks:
  platform_net:
    driver: bridge
