// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.3
//   protoc               v4.23.4
// source: proto/billing.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'billing';

export interface Empty {}

export const BILLING_PACKAGE_NAME = 'billing';

export interface BillingServiceClient {
  findAllBilling(request: Empty): Observable<Empty>;
}

export interface BillingServiceController {
  findAllBilling(request: Empty): Promise<Empty> | Observable<Empty> | Empty;
}

export function BillingServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['findAllBilling'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('BillingService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('BillingService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BILLING_SERVICE_NAME = 'BillingService';
